package MyApp;

import MyLibs.Manager;
import java.awt.Font;
import javax.swing.UIManager;
import MyLibs.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class CarRecordsForm extends javax.swing.JFrame {

    CarAddForm carForm;
    ProcessRentalForm processForm;
    ReportChooseForm chooseReport;

    public static CarRecords cars = new CarRecords();
    static CustRecords custs = new CustRecords();
    private static Manager loggedInManager;

    public static int choice;

    static ImageIcon info_icon = new ImageIcon("src/img/info_small.png");
    static ImageIcon error_icon = new ImageIcon("src/img/error_small.png");

    /**
     * Creates new form CarRecordsForm
     */
    public CarRecordsForm() {
        UIManager.put("OptionPane.messageFont", new Font("Verdana", Font.PLAIN, 12));
        UIManager.put("OptionPane.buttonFont", new Font("Verdana", Font.PLAIN, 11));
        initComponents();
    }

    public void replaceUserLabel() {
        loggedInLabel.setText(loggedInManager.getName());
    }

    public static Manager getLoggedInManager() {
        return loggedInManager;
    }

    public void setLoggedInManager(Manager loggedInManager) {
        this.loggedInManager = loggedInManager;
    }

    public static CarRecords getCars() {
        return cars;
    }

    public static CustRecords getCusts() {
        return custs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loggedAsLabel = new javax.swing.JLabel();
        loggedInLabel = new javax.swing.JLabel();
        recordCarButton = new javax.swing.JButton();
        processRentalButton = new javax.swing.JButton();
        statusReportButton = new javax.swing.JButton();
        programQuitButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loggedAsLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        loggedAsLabel.setText("Logged in as:");

        loggedInLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        loggedInLabel.setText("Placeholder");

        recordCarButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        recordCarButton.setText("Record a Car");
        recordCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordCarButtonActionPerformed(evt);
            }
        });

        processRentalButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        processRentalButton.setText("Process Rentals");
        processRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRentalButtonActionPerformed(evt);
            }
        });

        statusReportButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        statusReportButton.setText("View Reports");
        statusReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusReportButtonActionPerformed(evt);
            }
        });

        programQuitButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        programQuitButton.setText("Quit");
        programQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programQuitButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton1.setText("Load Cars");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(processRentalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(programQuitButton))
                    .addComponent(recordCarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedAsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loggedInLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedAsLabel)
                    .addComponent(loggedInLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordCarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processRentalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusReportButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programQuitButton)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordCarButtonActionPerformed
        carForm = new CarAddForm();
        carForm.setVisible(true);
    }//GEN-LAST:event_recordCarButtonActionPerformed

    private void processRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRentalButtonActionPerformed

        processForm = new ProcessRentalForm();
        processForm.setVisible(true);


    }//GEN-LAST:event_processRentalButtonActionPerformed

    private void statusReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusReportButtonActionPerformed
        chooseReport = new ReportChooseForm();
        chooseReport.setVisible(true);
    }//GEN-LAST:event_statusReportButtonActionPerformed

    private void programQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programQuitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_programQuitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Car Array1 = new Car(1, "Toyota", "Prius", 9999.99);
        Car Array2 = new Car(2, "Mitsubishi", "Lancer", 8888.88);
        Car Array3 = new Car(3, "Ford", "Mustang", 7777.77);
        Car Array4 = new Car(4, "Lamborghini", "Gallardo", 6666.66);
        Car Array5 = new Car(5, "Bugatti", "Type35", 5555.55);

        cars.allCars.add(Array1);
        cars.allCars.add(Array2);
        cars.allCars.add(Array3);
        cars.allCars.add(Array4);
        cars.allCars.add(Array5);

        Array1.setEndRent(new Date(0, 0, 0));
        Array2.setEndRent(new Date(0, 0, 0));
        Array3.setEndRent(new Date(0, 0, 0));
        Array4.setEndRent(new Date(0, 0, 0));
        Array5.setEndRent(new Date(0, 0, 0));

        JOptionPane.showMessageDialog(this,
                "Loaded cars from database.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE,
                CarRecordsForm.info_icon);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel loggedAsLabel;
    private javax.swing.JLabel loggedInLabel;
    private javax.swing.JButton processRentalButton;
    private javax.swing.JButton programQuitButton;
    private javax.swing.JButton recordCarButton;
    private javax.swing.JButton statusReportButton;
    // End of variables declaration//GEN-END:variables
}
