package MyApp;

import MyLibs.Date;
import MyLibs.LoginDetails;
import MyLibs.Manager;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class CarRecordsPasswordForm extends javax.swing.JFrame {
    CarRecordsForm main_form = new CarRecordsForm();
    ImageIcon info_icon = new ImageIcon("src/img/info_small.png");
    ImageIcon error_icon = new ImageIcon("src/img/error_small.png");

    /**
     * define all hard coded managers here
     * (these values are temporary, help in finalizing)
     */
    Manager test = new Manager("asdf",
            1,
            new LoginDetails("user", "pass"),
            new Date(1, 1, 1970));
    Manager test2 = new Manager("asdf 2",
            2,
            new LoginDetails("user2", "pass"),
            new Date(1, 1, 1970));
    
    /**
     * Creates new form CarRecordsPasswordForm
     */
    public CarRecordsPasswordForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginHeader = new javax.swing.JLabel();
        managerUsername = new javax.swing.JTextField();
        managerPassword = new javax.swing.JPasswordField();
        managerUsernameLabel = new javax.swing.JLabel();
        managerPasswordLabel = new javax.swing.JLabel();
        managerLoginButton = new javax.swing.JButton();
        programQuitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginHeader.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loginHeader.setText("Login to Car Rentals Management System");

        managerUsername.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        managerPassword.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N

        managerUsernameLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerUsernameLabel.setText("Username");

        managerPasswordLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerPasswordLabel.setText("Password");

        managerLoginButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        managerLoginButton.setText("Login");
        managerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLoginButtonActionPerformed(evt);
            }
        });

        programQuitButton.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        programQuitButton.setText("Exit");
        programQuitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programQuitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(managerUsernameLabel)
                    .addComponent(managerPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managerLoginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(programQuitButton)
                        .addGap(74, 74, 74))
                    .addComponent(managerPassword)
                    .addComponent(managerUsername))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(loginHeader)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerLoginButton)
                    .addComponent(programQuitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLoginButtonActionPerformed
        String enteredUser = managerUsername.getText();
        char[] enteredPass = managerPassword.getPassword();
        String passAsString = new String(enteredPass);

        switch (enteredUser) {
            case "user":
                managerLogin(test, enteredUser, passAsString);
                break;
            case "user2":
                managerLogin(test2, enteredUser, passAsString);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Login failed", "Message Box", JOptionPane.ERROR_MESSAGE, error_icon);
                break;
        }

    }//GEN-LAST:event_managerLoginButtonActionPerformed

    private void programQuitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programQuitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_programQuitButtonActionPerformed

    private void managerLogin(Manager m, String u, String p) {
        if (m.loginAttempt(u, p)) {
            JOptionPane.showMessageDialog(this, "Hello Manager " + m.getName(), "Message Box", JOptionPane.INFORMATION_MESSAGE, info_icon);
            this.setVisible(false);
            main_form.setVisible(true);
        } // Login passed
        else {
            JOptionPane.showMessageDialog(this, "Login failed", "Message Box", JOptionPane.ERROR_MESSAGE, error_icon);
        } // Login failed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("OptionPane.messageFont", new Font("Verdana", Font.PLAIN, 12));
        UIManager.put("OptionPane.buttonFont", new Font("Verdana", Font.PLAIN, 11));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRecordsPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRecordsPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRecordsPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRecordsPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRecordsPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginHeader;
    private javax.swing.JButton managerLoginButton;
    private javax.swing.JPasswordField managerPassword;
    private javax.swing.JLabel managerPasswordLabel;
    private javax.swing.JTextField managerUsername;
    private javax.swing.JLabel managerUsernameLabel;
    private javax.swing.JButton programQuitButton;
    // End of variables declaration//GEN-END:variables
}
